spring.application.name=acrm
server.port=3030

spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=Satendra

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true